"use client";
import { useEffect,useState } from "react";
import { Bell,CheckCircle2,LoaderCircle } from "lucide-react";

function keyBytes(value:string){const padded=value+"=".repeat((4-value.length%4)%4);const binary=atob(padded.replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(binary,c=>c.charCodeAt(0));}
const CURRENT_RELEASE="87-complete";

export function PushNotificationControl(){
  const [state,setState]=useState<"loading"|"off"|"on"|"unsupported">("loading");const [message,setMessage]=useState("");
  useEffect(()=>{(async()=>{if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window)){setState("unsupported");return;}const registration=await navigator.serviceWorker.register(`/sw.js?v=${CURRENT_RELEASE}`,{updateViaCache:"none"});await registration.update();const subscription=await registration.pushManager.getSubscription();setState(subscription?"on":"off");if(subscription){const json=subscription.toJSON();if(json.endpoint&&json.keys)void fetch("/api/push/subscription",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:json.endpoint,keys:json.keys})});const previous=localStorage.getItem("power-home-release");if(previous!==CURRENT_RELEASE&&Notification.permission==="granted"){const student=location.pathname.startsWith("/student");await registration.showNotification("پنل به‌روزرسانی شد",{body:"درگ‌ودراپ حرکات، خروج واضح از پنل و دکمه بستن پنجره‌ها اضافه شد.",icon:"/icon-512.png",badge:"/apple-touch-icon.png",tag:`release-${CURRENT_RELEASE}`,data:{url:student?"/student":"/coach"}});}localStorage.setItem("power-home-release",CURRENT_RELEASE);}})().catch(()=>setState("unsupported"));},[]);
  const toggle=async()=>{setMessage("");setState("loading");try{const registration=await navigator.serviceWorker.ready;const current=await registration.pushManager.getSubscription();if(current){await fetch("/api/push/subscription",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:current.endpoint})});await current.unsubscribe();setState("off");setMessage("اعلان خاموش شد.");return;}const isIos=/iPad|iPhone|iPod/.test(navigator.userAgent);const standalone=matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone;if(isIos&&!standalone){setState("off");setMessage("در آیفون اول Share را بزن، Add to Home Screen را انتخاب کن و بعد از داخل آیکن برنامه اعلان را فعال کن.");return;}const permission=await Notification.requestPermission();if(permission!=="granted"){setState("off");setMessage("اجازه اعلان داده نشد.");return;}const keyResponse=await fetch("/api/push/key",{cache:"no-store"});const keyData=await keyResponse.json() as {publicKey?:string;error?:string};if(!keyResponse.ok||!keyData.publicKey)throw new Error(keyData.error);const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(keyData.publicKey)});const json=subscription.toJSON();const response=await fetch("/api/push/subscription",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({endpoint:json.endpoint,keys:json.keys})});if(!response.ok)throw new Error("ثبت اعلان انجام نشد.");setState("on");setMessage("اعلان این دستگاه فعال شد.");}catch(error){setState("off");setMessage(error instanceof Error?error.message:"فعال‌سازی اعلان انجام نشد.");}};
  if(state==="unsupported")return <div className="push-control unsupported"><Bell/><span>برای دریافت اعلان، لینک را در Safari باز کن و «Add to Home Screen» را بزن.</span></div>;
  return <div className={`push-control ${state==="on"?"enabled":""}`}><button type="button" onClick={toggle} disabled={state==="loading"} aria-pressed={state==="on"}>{state==="loading"?<LoaderCircle className="animate-spin"/>:state==="on"?<CheckCircle2 className="push-enabled-check"/>:<Bell/>}<span>{state==="on"?"اعلان فعال است":"فعال‌کردن اعلان"}</span></button>{message&&<small>{message}</small>}</div>;
}
